offsetScaledLogVariance: change it to unsigned short (SCA _032 #65)
Avnu/gptp pull request #77
Opened 2021-01-21 16:00 UTC by PawelModrzejewski

Static code analysis fix _032 (Issue #65)

SCA complains here about ntohs() but the real issue is the type of offsetScaledLogVariance,
which currently in the code is int16_t. There seems to be inconsistency in IEEE 802.1AS-2011:

    - in 6.3.3.8 ClockQuality offsetScaledLogVariance is defined as UInteger16;
    - later in the document it's used as Integer16 (Table 14-1, code examples etc.);

This inconsistency has been corrected in IEEE 802.1AS-2011/Cor 1-2013 where UInteger16 was specified
in the Table 14-1 and used later in the code examples. IEEE 1588-2008 defines offsetScaledLogVariance also
as UInteger16 (see 5.3.7 ClockQuality).

2021-01-21 16:02 UTC, PawelModrzejewski commented
Please review

2021-02-09 07:48 UTC, PawelModrzejewski commented
Hello, hello! Any comments here?

2021-03-02 17:15 UTC, PawelModrzejewski commented
Anybody out there?

2023-02-28 10:38 UTC, MarcinMiklas requested changes

2023-02-28 10:38 UTC, MarcinMiklas commented on linux/shm_test/shm_test.cpp
> +    fprintf(stdout, "offset_scaled_log_variance %d\n", (unsigned int) ptpData->offset_scaled_log_variance);
%u should be used for printing unsigned int

2023-03-03 09:33 UTC, MarcinMiklas approved these changes

2023-03-03 09:33 UTC, merged